### ISSUE TITLE
npx schluessel edit does not open editor (sublime) on macOS Catalina 10.15.3

### ISSUE THREAD

**Issue by iAnton** [Pik-9/schluessel#1]
run `npx schluessel edit` but nothing happen,
on RoR project `rails credentials:edit` works as expected

cat ~/.zshrc
...
export EDITOR="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl --wait"

**Comment by Pik-9** [comment]
Hi iAnton,
thanks for reporting.

Can you try it with 0.1.6 again, please?

**Comment by iAnton** [comment]
Hi @Pik-9,
It works now. Thank you!
